/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IMG_H_RPCGEN
#define _IMG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct argimg {
	uint16_t largeur;
	uint16_t hauteur;
	struct {
		u_int imgE_len;
		char *imgE_val;
	} imgE;
	uint16 n;
	uint16 m;
	struct {
		u_int imgS_len;
		char *imgS_val;
	} imgS;
};
typedef struct argimg argimg;

#define IMGPROG 0x20000000
#define PROGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MoyFiltr_prog_1 1
extern  argimg * moyfiltr_prog_1_1(argimg *, CLIENT *);
extern  argimg * moyfiltr_prog_1_1_svc(argimg *, struct svc_req *);
#define MedFiltr_prog_2 2
extern  argimg * medfiltr_prog_2_1(argimg *, CLIENT *);
extern  argimg * medfiltr_prog_2_1_svc(argimg *, struct svc_req *);
extern int imgprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MoyFiltr_prog_1 1
extern  argimg * moyfiltr_prog_1_1();
extern  argimg * moyfiltr_prog_1_1_svc();
#define MedFiltr_prog_2 2
extern  argimg * medfiltr_prog_2_1();
extern  argimg * medfiltr_prog_2_1_svc();
extern int imgprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_argimg (XDR *, argimg*);

#else /* K&R C */
extern bool_t xdr_argimg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IMG_H_RPCGEN */
