/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "img.h"


void
imgprog_1(char *host)
{
	CLIENT *clnt;
	argimg  *result_1;
	argimg  moyfiltr_prog_1_1_arg;
	argimg  *result_2;
	argimg  medfiltr_prog_2_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, IMGPROG, PROGVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = moyfiltr_prog_1_1(&moyfiltr_prog_1_1_arg, clnt);
	if (result_1 == (argimg *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = medfiltr_prog_2_1(&medfiltr_prog_2_1_arg, clnt);
	if (result_2 == (argimg *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	imgprog_1 (host);
exit (0);
}
