/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "img.h"

bool_t
xdr_argimg (XDR *xdrs, argimg *objp)
{
	register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->largeur))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->hauteur))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->imgE.imgE_val, (u_int *) &objp->imgE.imgE_len, 2500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_uint16 (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_uint16 (xdrs, &objp->m))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->imgS.imgS_val, (u_int *) &objp->imgS.imgS_len, 2500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
