/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "img.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

argimg *
moyfiltr_prog_1_1(argimg *argp, CLIENT *clnt)
{
	static argimg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MoyFiltr_prog_1,
		(xdrproc_t) xdr_argimg, (caddr_t) argp,
		(xdrproc_t) xdr_argimg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

argimg *
medfiltr_prog_2_1(argimg *argp, CLIENT *clnt)
{
	static argimg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MedFiltr_prog_2,
		(xdrproc_t) xdr_argimg, (caddr_t) argp,
		(xdrproc_t) xdr_argimg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
